Virtual contests with upsolving
apathism/ejstand pull request #1
Opened 2021-02-17 19:52 UTC by eropsergeev

2021-02-17 22:56 UTC, apathism requested changes

2021-02-17 22:56 UTC, apathism commented on src/EjStand/Models/Standing.hs
> +                                     , virtualDeadlines       :: !Bool
Предлагаю вместо двух опций сделать одну, потому что virtualContestsTime подразумевает наличие virtualDeadlines.

```haskell
virtualDeadlines :: !(Maybe Integer)
```

2021-02-17 22:56 UTC, apathism commented on src/EjStand/StandingBuilder.hs
> +            case getVirtualStart src prob user of
Мне кажется, тут нет смысл разворачивать Maybe с помощью case.
Можно было бы сделать fmap вместо всего case.

```haskell
addUTCTime время <$> getVirtualStart src prob user
```

2021-02-17 22:56 UTC, apathism commented on src/EjStand/StandingBuilder.hs
> +                Just time -> Just (addUTCTime (realToFrac virtualContestsTime) time)
`fromInteger` лучше, чем `realToFrac`

2021-02-17 23:04 UTC, apathism commented on src/EjStand/StandingBuilder.hs
> +            case getVirtualStart src prob user of
Ну, или даже если время — это Maybe Integer, то можно вообще сделать через do:

```haskell
virtualDeadline = do
    time <- virtualDeadlines
    virtualStart <- getVirtualStart src prob user
    return $ addUTCTime time virtualStart
```

2021-02-19 22:54 UTC, eropsergeev commented
Переписал. Заодно добавил возможность делать свой скоринг

2021-02-20 21:52 UTC, apathism commented
> Переписал. Заодно добавил возможность делать свой скоринг

Предлагаю вливать разные фичи в отдельных PR. Давай скоринг отдельным?

2021-02-21 11:11 UTC, closed without merging